# -----------------[NoStrip]-------------------
# --------------[Toggle Message]---------------
# Available Toggle message placeholders for toggle status
# {status} = on | off
# {astatus} = enabled | disabled
# ---------------------------------------------
# -------------[Help/command Menu]------------------------------------------------------------------
# Whether or not players can see the NoStrip menu/commands in chat with the /nostrip command
# allow-help-menu: true/false
# --------------------------------------------------------------------------------------------------

allow-help-menu: true

messages:
  prefix: '&8&l[&c&l⦸ &4&lNo&c&lStrip &c&l⦸&8&l]'
  unknown-command: '&cUnknown Command'
  must-be-player: '&cYou Must Be A Player To Use This Command!'
  no-permission: '&cPermission Required! Contact server admin!'
  no-axe-permission: '&cAxe Is Denied! Permission Required!'
  toggle-message: '&2Log Stripping {status}'
  config-reloaded: '&2Config Reloaded!'